Repository zanemooney/robofriends_cis486, pull requests merged in 2022-03, with the labels that each got.

#9 Moved button from Button.js to Card.js
  src/App.js
  src/Button.js
  src/Card.js
Labels: front-end

#12 installed react-icons
  package-lock.json
  package.json
  src/BoyDevs.js
  src/GirlDevs.js
  src/assets/down.png
  src/assets/up.png
Labels: enhancement

#15 Completed dev cards
  src/App.css
  src/BoyDevs.js
  src/GirlDevs.js
Labels: front-end

#18 react icons up and down
  src/Card.js
Labels: enhancement, front-end

#21 Iss17
  src/App.css
  src/App.js
  src/BoyDevs.js
  src/Card.js
  src/GirlDevs.js
  src/index.css
  src/index.js
Labels: front-end
